// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwQAUH9P39XHkLTCXh1f-6KKt-QL8di8I',
    appId: '1:415003902258:web:9684e3f5c988251bb6172b',
    messagingSenderId: '415003902258',
    projectId: 'sistema-gimnasios-92eb2',
    authDomain: 'sistema-gimnasios-92eb2.firebaseapp.com',
    storageBucket: 'sistema-gimnasios-92eb2.firebasestorage.app',
    measurementId: 'G-ZJY8QFZ3FJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3GQroi0uPmjzPZExVl2ipx5OQw62pSjE',
    appId: '1:415003902258:android:c9543f02deac8af1b6172b',
    messagingSenderId: '415003902258',
    projectId: 'sistema-gimnasios-92eb2',
    storageBucket: 'sistema-gimnasios-92eb2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBINFwTVZV_ORJMWyrFGTHIf-f7PfYKaDE',
    appId: '1:415003902258:ios:ef93ca6e66304101b6172b',
    messagingSenderId: '415003902258',
    projectId: 'sistema-gimnasios-92eb2',
    storageBucket: 'sistema-gimnasios-92eb2.firebasestorage.app',
    iosBundleId: 'com.example.sistemaGym',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBINFwTVZV_ORJMWyrFGTHIf-f7PfYKaDE',
    appId: '1:415003902258:ios:ef93ca6e66304101b6172b',
    messagingSenderId: '415003902258',
    projectId: 'sistema-gimnasios-92eb2',
    storageBucket: 'sistema-gimnasios-92eb2.firebasestorage.app',
    iosBundleId: 'com.example.sistemaGym',
  );
}
